name: Update Airflow DAG Status

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      git_rev:
        description: 'The git revision to deploy'
        required: false
        default: ''

jobs:
  update-dag-status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install apache-airflow requests

      - name: Run script
        working-directory: ./
        env:
            AIRFLOW_API_URL: ${{ secrets.AIRFLOW_API_URL }}
            AIRFLOW_API_TOKEN: ${{ secrets.AIRFLOW_API_TOKEN }}
        run: python .github/scripts/dag_runs.py

      - name: Check for changes and perform commit and push
        run: |
          git_status=$(git status --porcelain)
          if [ -n "$git_status" ]; then
            echo "Changes found"
            git config --global user.name "airflow-oss-bot"
            git config --global user.email "airflow-oss-bot@astronomer.io"
            git add dag_run_statuses.json
            git commit -m "Update DAG run statuses"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
